# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: object652
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dexo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: local2

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"
